$(document).ready(function() {
	$('#heading1').click(function(){ 
		$("li.heading1").toggle('slow')
		});
	$('#heading2').click(function(){ 
		$("li.heading2").toggle('slow')
	});
	$('#heading3').click(function(){ 
		$("li.heading3").toggle('slow')
	});
	$('#heading4').click(function(){ 
		$("li.heading4").toggle('slow')
	});
	$('#heading5').click(function(){ 
		$("li.heading5").toggle('slow')
	});
	$('#heading6').click(function(){ 
		$("li.heading6").toggle('slow')
	});
});